#!/bin/bash
opt=1
while [ "$opt" -lt 6 ]
do

echo -e "Choose one of the Following\n1. Create a New Address Book\n2. View Records\n3. Insert new Record\n4. Delete a Record\n5. Modify a Record\n6. Exit"

read opt
case $opt in
